### ISSUE TITLE
java.net.URISyntaxException: Illegal character in path at index 80: http://0.0.0.0//shop/product-details/31/228/Gamis+Mix+Combined+V-Embroidery.html</iframe>

### ISSUE THREAD

**Issue by ceefour** [ocpsoft/rewrite#197]
rewrite 2.0.12.Final

I got the following error in Tomcat7's `localhost.log` which seems to be hacking attempt (?) but rewrite throws exception. It should log the error (perhaps `INFO`, since the client can give all kinds of invalid URIs) but not cause the server to fail.

```
Jan 05, 2015 6:34:36 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Filtered request failed.] with root cause
java.net.URISyntaxException: Illegal character in path at index 80: http://0.0.0.0//shop/product-details/31/228/Gamis+Mix+Combined+V-Embroidery.html</iframe>
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at org.ocpsoft.urlbuilder.util.Decoder.path(Decoder.java:14)
        at org.ocpsoft.urlbuilder.AddressBuilder.pathEncoded(AddressBuilder.java:147)
        at org.ocpsoft.urlbuilder.AddressBuilderPort.pathEncoded(AddressBuilderPort.java:54)
        at org.ocpsoft.rewrite.servlet.impl.BaseHttpRewrite.getInboundAddress(BaseHttpRewrite.java:88)
        at org.ocpsoft.rewrite.servlet.config.Path.evaluateHttp(Path.java:119)
        at org.ocpsoft.rewrite.servlet.config.HttpCondition.evaluate(HttpCondition.java:44)
        at org.ocpsoft.rewrite.config.And.evaluate(And.java:77)
        at org.ocpsoft.rewrite.config.RuleBuilder.evaluate(RuleBuilder.java:129)
        at org.ocpsoft.rewrite.config.And.evaluate(And.java:77)
        at org.ocpsoft.rewrite.config.RuleBuilder.evaluate(RuleBuilder.java:129)
        at org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider.rewriteHttp(DefaultHttpRewriteProvider.java:165)
        at org.ocpsoft.rewrite.servlet.http.HttpRewriteProvider.rewrite(HttpRewriteProvider.java:43)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:247)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.soluvas.web.site.servlet.ShiroPrincipalsServletFilter.doFilter(ShiroPrincipalsServletFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.soluvas.web.site.servlet.MoreMdcServletFilter.doFilter(MoreMdcServletFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:104)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2378)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by chkal** [comment]
Thanks for reporting this. Yeah, I think we should rework the URL decoding. I'll work on this in the next weeks...

**Comment by chkal** [comment]
I think this should be fixed now. Basically I implemented the percent-decoding myself in a very fault-tolerant way. This way Rewrite won't fail any more if the client requests not well-formed URLs.

@lincolnthree Any thoughts? Should I merge this to master? All tests are green. ;)

**Comment by mcenkar** [comment]
Any plans of releasing rewrite with this fixed? It's affecting us in production and i would rather upgrade to version with bug fixed than create workarounds if possible.

**Comment by chkal** [comment]
@mcenkar Did you give this branch a try? It would be helpful if you could verify that my patch fixes the problem.

**Comment by mcenkar** [comment]
@chkal I had a quick look and it seems to be OK. At least it can handle few cases which it couldn't before :)

**Comment by chkal** [comment]
Thanks @mcenkar. 

Unfortunately I currently don't find much time for working on Rewrite. There are still some issue we should address before releasing 4.0.0.Final. But perhaps we can push out another Alpha soon.

**Comment by lincolnthree** [comment]
Yeah, I think this should be merged in. It looks good.

**Comment by chkal** [comment]
Great. I just rebased and merged to master.
