### ISSUE TITLE
org.ocpsoft.rewrite.config.Filesystem fail on windows

### ISSUE THREAD

**Issue by cpuy** [ocpsoft/rewrite#199]
Hi,

when using Filesystem.fileExists(file) on windows, this fails with message `java.lang.IllegalArgumentException: Character at starting position is escaped, and cannot be used in capturing a group.`

Please note that it also fail when using org.ocpsoft.rewrite.servlet.config.Stream and mainly everywhere that use `new RegexParameterizedPatternParser(resource.getAbsolutePath());` cause getAbsolutePath() returns path with `\` on windows.

Here is a simple unit test that show the errors, simply launch it on windows to see exception.

```java
import java.io.File;

import org.junit.Assert;
import org.junit.Test;
import org.ocpsoft.rewrite.config.Filesystem;

public class RewriteTest {

    @Test
    public void testFileSystemWindows() throws Exception {
        File tmpDir = new File("c:\\tmp");
        File file = new File(tmpDir, "{param}.txt");


        try {
            Filesystem.fileExists(file);
        } catch (Exception e) {
            Assert.fail("should not fail here");
        }
    }
}
```

**Comment by chkal** [comment]
You could please post the full stacktrace? I've no Windows box available to test this myself.

**Comment by chkal** [comment]
By the way, I think you can work around that problem by using `/` instead. AFAIK this will also work with `File`:

    File tmpDir = new File("c:/tmp");

**Comment by cpuy** [comment]
Please see stacktrace below.

Of course `File tmpDir = new File("c:/tmp");` works but as I said above, `tmpDir.getAbsolutePath()` will always returns path with `\` on windows.

So there are no workaround.

**Comment by cpuy** [comment]
java.lang.IllegalArgumentException: Character at starting position is escaped, and cannot be used in capturing a group.
	at org.ocpsoft.rewrite.util.ParseTools.balancedCapture(ParseTools.java:51)
	at org.ocpsoft.rewrite.param.RegexParameterizedPatternParser.<init>(RegexParameterizedPatternParser.java:106)
	at org.ocpsoft.rewrite.param.RegexParameterizedPatternParser.<init>(RegexParameterizedPatternParser.java:65)
	at org.ocpsoft.rewrite.config.Filesystem.<init>(Filesystem.java:46)
	at org.ocpsoft.rewrite.config.Filesystem.fileExists(Filesystem.java:86)
	at com.bonitasoft.web.form.workspace.WidgetDirectiveLoader.getConfiguration(WidgetDirectiveLoader.java:34)
	at com.bonitasoft.web.form.workspace.WidgetDirectiveLoader.getConfiguration(WidgetDirectiveLoader.java:26)
	at org.ocpsoft.rewrite.annotation.handler.RewriteConfigurationHandler.process(RewriteConfigurationHandler.java:63)
	at org.ocpsoft.rewrite.annotation.handler.RewriteConfigurationHandler.process(RewriteConfigurationHandler.java:32)
	at org.ocpsoft.rewrite.annotation.HandlerChainImpl.proceed(HandlerChainImpl.java:41)
	at org.ocpsoft.rewrite.annotation.ClassVisitorImpl.visit(ClassVisitorImpl.java:157)
	at org.ocpsoft.rewrite.annotation.ClassVisitorImpl.visit(ClassVisitorImpl.java:88)
	at org.ocpsoft.rewrite.annotation.scan.AbstractClassFinder.processClass(AbstractClassFinder.java:202)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.handleClassEntry(WebClassesFinder.java:188)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.processDirectory(WebClassesFinder.java:144)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.processDirectory(WebClassesFinder.java:140)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.processDirectory(WebClassesFinder.java:140)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.processDirectory(WebClassesFinder.java:140)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.processDirectory(WebClassesFinder.java:140)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.processDirectory(WebClassesFinder.java:140)
	at org.ocpsoft.rewrite.annotation.scan.WebClassesFinder.findClasses(WebClassesFinder.java:76)
	at org.ocpsoft.rewrite.annotation.config.AnnotationConfigProvider.getConfiguration(AnnotationConfigProvider.java:133)
	at org.ocpsoft.rewrite.annotation.config.AnnotationConfigProvider.getConfiguration(AnnotationConfigProvider.java:39)
	at org.ocpsoft.rewrite.config.ConfigurationLoader.build(ConfigurationLoader.java:137)
	at org.ocpsoft.rewrite.config.ConfigurationLoader.buildCached(ConfigurationLoader.java:117)
	at org.ocpsoft.rewrite.config.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:80)
	at org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider.init(DefaultHttpRewriteProvider.java:72)
	at org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider.init(DefaultHttpRewriteProvider.java:48)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.init(RewriteFilter.java:137)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4828)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5508)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by chkal** [comment]
Ah, OK, got it.

@lincolnthree One question. Is the `pattern` constructor argument here supposed to be a regular expression?

https://github.com/ocpsoft/rewrite/blob/fd2cbe7b8ad071882d5daf58b49954289ab48e83/api/src/main/java/org/ocpsoft/rewrite/param/RegexParameterizedPatternParser.java#L63

I think actually not. It is expected to be something like `/foobar/{param}/test.txt` where `.` actually means `.` and not "any character". Correct?

**Comment by lincolnthree** [comment]
Ah, interesting. We don't see much use on Windows, so I guess this hasn't come up before :)

The pattern here is not a regular expression, it is a ParameterizedPattern (a type of our own invention), and that means it uses '\' as an escape character. I'm looking in to the issue.

**Comment by lincolnthree** [comment]
Hi. I've resolved this issue (and fixed another issue with proper escape handling in parameterized patterns in general. I'm uploading snapshots to the sonatype nexus repository. You can add this repository to your POM and pull down the latest snapshots.

3.0.0-SNAPSHOT

```
<!-- To use snapshots, you must also use the Sonatype Snapshots respository -->
<repository>
   <id>sonatype-snapshots</id>
   <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>
```
