### ISSUE TITLE
CDI integration fails with multiple web project in EAR

### ISSUE THREAD

**Issue by fzoli** [ocpsoft/rewrite#212]
Hi,

I write an enterprise application that contains two web project.
Base rewrite functions work in both project and I can use CDI integration one of them.
If I use CDI integration in both project, it fails in application deploy time.

Here you find a sample project with log file:
http://lanitex.hu/Sample.zip

The startup log:

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=192m; support was removed in 8.0
Launching GlassFish on Felix platform
máj. 30, 2015 10:42:26 DU com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner createBundleProvisioner
INFO: Create bundle provisioner class = class com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner.
máj. 30, 2015 10:42:26 DU com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner$DefaultCustomizer getLocations
WARNING: Skipping entry  because it is not an absolute URI.
máj. 30, 2015 10:42:26 DU com.sun.enterprise.glassfish.bootstrap.osgi.BundleProvisioner$DefaultCustomizer getLocations
WARNING: Skipping entry  because it is not an absolute URI.
Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishRuntime@344b21fa in service registry.
Found populator: com.sun.enterprise.v3.server.GFDomainXml
#!## LogManagerService.postConstruct : rootFolder=/usr/local/glassfish-4.1/glassfish
#!## LogManagerService.postConstruct : templateDir=/usr/local/glassfish-4.1/glassfish/lib/templates
#!## LogManagerService.postConstruct : src=/usr/local/glassfish-4.1/glassfish/lib/templates/logging.properties
#!## LogManagerService.postConstruct : dest=/home/zoli/.netbeans/8.0.2/config/GF_4.1_7/domain1/config/logging.properties
Info:   Running GlassFish Version: GlassFish Server Open Source Edition  4.1  (build 13)
Info:   Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter
Info:   Realm [admin-realm] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.
Info:   Realm [file] of classtype [com.sun.enterprise.security.auth.realm.file.FileRealm] successfully created.
Info:   Realm [certificate] of classtype [com.sun.enterprise.security.auth.realm.certificate.CertificateRealm] successfully created.
Info:   Authorization Service has successfully initialized.
Info:   HV000001: Hibernate Validator 5.0.0.Final
Info:   Registered org.glassfish.ha.store.adapter.cache.ShoalBackingStoreProxy for persistence-type = replicated in BackingStoreFactoryRegistry
Info:   Grizzly Framework 2.3.15 started in: 35ms - bound to [/0.0.0.0:8080]
Info:   Grizzly Framework 2.3.15 started in: 1ms - bound to [/0.0.0.0:8181]
Info:   Grizzly Framework 2.3.15 started in: 1ms - bound to [/0.0.0.0:4848]
Info:   Grizzly Framework 2.3.15 started in: 0ms - bound to [/0.0.0.0:3700]
Info:   GlassFish Server Open Source Edition  4.1  (13) startup time : Felix (1 684ms), startup services(666ms), total(2 350ms)
Info:   JMXStartupService has started JMXConnector on JMXService URL service:jmx:rmi://PC-Farkas:8686/jndi/rmi://PC-Farkas:8686/jmxrmi
Info:   Grizzly Framework 2.3.15 started in: 1ms - bound to [/0.0.0.0:7676]
Info:   Registered com.sun.enterprise.glassfish.bootstrap.osgi.EmbeddedOSGiGlassFishImpl@7dcb42a9 as OSGi service registration: org.apache.felix.framework.ServiceRegistrationImpl@6215366a.
Info:   Grizzly Framework 2.3.15 started in: 9ms - bound to [/0.0.0.0:8181]
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   visiting unvisited references
Info:   Java security manager is disabled.
Info:   Entering Security Startup Service.
Info:   Loading policy provider com.sun.enterprise.security.provider.PolicyWrapper.
Info:   Security Service(s) started successfully.
Info:   Created HTTP listener http-listener-1 on host/port 0.0.0.0:8080
Info:   Created HTTP listener http-listener-2 on host/port 0.0.0.0:8181
Info:   Created HTTP listener admin-listener on host/port 0.0.0.0:4848
Info:   Created virtual server server
Info:   Created virtual server __asadmin
Info:   Setting JAAS app name glassfish-web
Info:   Virtual server server loaded default web module 
Info:   WELD-000900: 2.2.2 (Final)
WARN:   WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
WARN:   WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.gf.cdi.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.gf.cdi.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.gf.cdi.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.gf.cdi.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Info:   RewriteFilter starting up...
Severe:   WebModule[/Sample-web]Exception starting filter OCPsoft Rewrite Filter
java.lang.InstantiationException
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:135)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:5329)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:5943)
    at com.sun.enterprise.web.WebModule.start(WebModule.java:691)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1041)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:1024)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:747)
    at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2286)
    at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1932)
    at com.sun.enterprise.web.WebApplication.start(WebApplication.java:139)
    at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
    at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
    at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:500)
    at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
    at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:539)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:535)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:360)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:534)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:565)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:557)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:360)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:556)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1464)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:109)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1846)
    at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1722)
    at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
    at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
    at org.glassfish.grizzly.http.server.StaticHttpHandlerBase.service(StaticHttpHandlerBase.java:189)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error instantiating class org.ocpsoft.rewrite.cdi.bridge.RewriteLifecycleEventBridge
    at org.ocpsoft.common.services.ServiceLoader.loadEnriched(ServiceLoader.java:342)
    at org.ocpsoft.common.services.ServiceLoader.loadClass(ServiceLoader.java:243)
    at org.ocpsoft.common.services.ServiceLoader.loadService(ServiceLoader.java:234)
    at org.ocpsoft.common.services.ServiceLoader.loadServiceFile(ServiceLoader.java:196)
    at org.ocpsoft.common.services.ServiceLoader.reload(ServiceLoader.java:145)
    at org.ocpsoft.common.services.ServiceLoader.iterator(ServiceLoader.java:394)
    at org.ocpsoft.common.util.Iterators.asList(Iterators.java:40)
    at org.ocpsoft.rewrite.servlet.RewriteFilter.init(RewriteFilter.java:82)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:275)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:131)
    ... 51 more
Caused by: java.lang.IllegalArgumentException: Can not set javax.enterprise.inject.spi.BeanManager field org.ocpsoft.rewrite.cdi.bridge.RewriteLifecycleEventBridge.manager to org.ocpsoft.rewrite.cdi.bridge.RewriteLifecycleEventBridge
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
    at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
    at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
    at java.lang.reflect.Field.set(Field.java:764)
    at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:94)
    at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:365)
    at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:376)
    at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:70)
    at org.glassfish.weld.services.InjectionServicesImpl.aroundInject(InjectionServicesImpl.java:172)
    at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)
    at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:65)
    at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:109)
    at org.ocpsoft.rewrite.cdi.CdiServiceEnricher.enrich(CdiServiceEnricher.java:77)
    at org.ocpsoft.common.services.ServiceLoader.loadEnriched(ServiceLoader.java:324)
    ... 60 more

Info:   Loading application [Sample-ear-0.0.1-SNAPSHOT#Sample-web-0.0.1-SNAPSHOT.war] at [/Sample-web]
Info:   RewriteFilter starting up...
Info:   Loaded [4] org.ocpsoft.rewrite.servlet.spi.RewriteLifecycleListener [org.ocpsoft.rewrite.cdi.bridge.RewriteLifecycleEventBridge<-100>, org.ocpsoft.rewrite.cdi.bridge.RewriteLifecycleEventBridge<-100>, org.ocpsoft.rewrite.servlet.config.lifecycle.JoinRewriteLifecycleListener<2147483647>, org.ocpsoft.rewrite.servlet.impl.DefaultRewriteLifecycleListener<2147483647>]
Info:   Loaded [3] org.ocpsoft.rewrite.servlet.spi.RequestCycleWrapper [org.ocpsoft.rewrite.cdi.bridge.RequestCycleWrapperBridge<0>, org.ocpsoft.rewrite.cdi.bridge.RequestCycleWrapperBridge<0>, org.ocpsoft.rewrite.servlet.impl.HttpRewriteRequestCycleWrapper<0>]
Info:   Loaded [3] org.ocpsoft.rewrite.spi.RewriteProvider [org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider<0>, org.ocpsoft.rewrite.cdi.bridge.RewriteProviderBridge<100>, org.ocpsoft.rewrite.cdi.bridge.RewriteProviderBridge<100>]
Info:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.RewriteResultHandler [org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler<0>]
Info:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.InboundRewriteProducer [org.ocpsoft.rewrite.servlet.impl.HttpInboundRewriteProducer<0>]
Info:   Loaded [1] org.ocpsoft.rewrite.servlet.spi.OutboundRewriteProducer [org.ocpsoft.rewrite.servlet.impl.HttpOutboundRewriteProducer<0>]
Info:   Loaded [0] org.ocpsoft.rewrite.servlet.spi.ContextListener []
Info:   Loaded [0] org.ocpsoft.rewrite.servlet.spi.RequestListener []
Info:   Loaded [0] org.ocpsoft.rewrite.servlet.spi.RequestParameterProvider []
Info:   Loaded [2] org.ocpsoft.rewrite.el.spi.ExpressionLanguageProvider [org.ocpsoft.rewrite.cdi.CdiExpressionLanguageProvider<10>, org.ocpsoft.rewrite.cdi.CdiExpressionLanguageProvider<10>]
Info:   Loaded [0] org.ocpsoft.rewrite.spi.InvocationResultHandler []
Info:   Loaded [2] org.ocpsoft.common.spi.ServiceEnricher [org.ocpsoft.rewrite.cdi.CdiServiceEnricher, org.ocpsoft.rewrite.cdi.CdiServiceEnricher]
Info:   Loaded [1] org.ocpsoft.rewrite.spi.ConfigurationCacheProvider [org.ocpsoft.rewrite.servlet.impl.ServletContextConfigurationCacheProvider<0>]
Info:   Loaded [1] org.ocpsoft.rewrite.config.ConfigurationProvider [org.ocpsoft.rewrite.annotation.config.AnnotationConfigProvider<100>]
Info:   Loaded [0] org.ocpsoft.rewrite.spi.RuleCacheProvider []
Warning:   Cannot find classes folder: /WEB-INF/classes/
Info:   Rewrite 2.0.12.Final initialized.
Info:   Loading application [Sample-ear-0.0.1-SNAPSHOT#Sample-admin-web-0.0.1-SNAPSHOT.war] at [/Sample-admin-web]
Info:   Sample-ear-0.0.1-SNAPSHOT was successfully deployed in 4 977 milliseconds.
Info:   Created HTTP listener http-listener-1 on host/port 0.0.0.0:8080
Info:   Grizzly Framework 2.3.15 started in: 3ms - bound to [/0.0.0.0:8080]
```

Zoli

**Comment by chkal** [comment]
Hmmm. Weird. I see no reason why this should fail.

https://github.com/ocpsoft/rewrite/blob/c960607c4f3a4d099aea4d0a0dc1548b3e29feca/integration-cdi/src/main/java/org/ocpsoft/rewrite/cdi/bridge/RewriteLifecycleEventBridge.java#L36-37

Actually Weld is failing here. I've no idea why. Is Rewrite located in the EAR's or in the WAR's lib directory?

**Comment by fzoli** [comment]
Rewrite is in the WAR's lib directory.

Here's the maven config:

web apps:
```
<dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-web-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>
        <!-- Rewrite -->
        <dependency>
            <groupId>org.ocpsoft.rewrite</groupId>
            <artifactId>rewrite-servlet</artifactId>
            <version>2.0.12.Final</version>
        </dependency>
        <dependency>
            <groupId>org.ocpsoft.rewrite</groupId>
            <artifactId>rewrite-integration-cdi</artifactId>
            <version>2.0.12.Final</version>
        </dependency>
 </dependencies>
```

ear:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-ear-plugin</artifactId>
                <version>2.8</version>
                <configuration>
                    <version>6</version>
                    <defaultLibBundleDir>lib</defaultLibBundleDir>
                    <modules>
                        <webModule>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>Sample-web</artifactId>
                        </webModule>
                        <webModule>
                            <groupId>${project.groupId}</groupId>
                            <artifactId>Sample-admin-web</artifactId>
                        </webModule>
                    </modules>
                </configuration>
            </plugin>
```

**Comment by chkal** [comment]
Hey, thanks for providing these details.

However, I don't think that this is a bug in Rewrite. Looks like some Glassfish/Weld issue to me. Rewrite is basically using the CDI API to process `@Inject` annotated fields on an existing object. Weld then fails with an `IllegalArgumentException` when using `Field.set()` on the BeanManager field. According to the javadocs of `Field.set()` this exception occurs when:

> if the specified object is not an instance of the class or interface declaring the underlying field (or a subclass or implementor thereof), or if an unwrapping conversion fails.

So, IMO this is more a Weld issue..

**Comment by urugator** [comment]
Not sure if this is the cause, but you might want to check this:
http://balusc.blogspot.cz/2013/10/cdi-behaved-unexpectedly-in-ear-so.html

**Comment by garcia-jj** [comment]
Just for information: I have and EAR application with 3 WARs using rewrite `3.4.1.Final` under Wildfly 10.1 and all works fine. All WARs have rewrite inside its own WEB-INF/lib directory.
