### ISSUE TITLE
Redirect.permanent() throws ParameterizationException

### ISSUE THREAD

**Issue by JensPiegsa** [ocpsoft/rewrite#214]
My configuration looks like this:
```java
return ConfigurationBuilder.begin()

// # Rule 0
.addRule()
.perform(Log.message(Level.DEBUG, "### ocpsoft rewrite is active ###"))

// # Rule 1
.addRule()
.when(Direction.isInbound().and(Path.matches("{path}")))
.perform(Log.message(Level.INFO, "Client requested path: {path}"))
.where("path").matches(".*")

// # Rule 2
.addRule()
.when(Direction.isInbound().and(Path.matches("/")))
.perform(Redirect.permanent(context.getContextPath() + "/{languagecode}/"))
.where("languagecode").bindsTo(PhaseBinding.to(El.property("#{language.code}")).after(PhaseId.RESTORE_VIEW))

// # Rule 3
.addRule(Join.path("/{languagecode}/").to("/index.xhtml").withInboundCorrection())
.when(Direction.isInbound())
.where("languagecode").matches("\\w{2}").bindsTo(PhaseBinding.to(El.property("#{language.code}")).after(PhaseId.RESTORE_VIEW))
;
```

Rule 0, 1 and 3 work, Rule 2 doesn't. Please see the stack trace for the latter below.

I'm using `rewrite-servlet` and `rewrite-integration-faces` and have tried this out with 
`2.0.12.Final` and `3.0.0-SNAPSHOT` running on Wildfly `9.0.1.Final`.

Stack trace:

```
06:55:47,666 ERROR [io.undertow.request] (default task-19) UT005023: Exception handling request to /transfer/: javax.servlet.ServletException: Error during Rewrite processing. Please inspect stack trace for root cause.
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:194)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.ocpsoft.rewrite.exception.ParameterizationException: The value of required parameter [languagecode] was null.
        at org.ocpsoft.rewrite.param.RegexParameterizedPatternBuilder.extractBoundValues(RegexParameterizedPatternBuilder.java:262)
        at org.ocpsoft.rewrite.param.RegexParameterizedPatternBuilder.build(RegexParameterizedPatternBuilder.java:136)
        at org.ocpsoft.rewrite.servlet.config.Redirect.performHttp(Redirect.java:58)
        at org.ocpsoft.rewrite.servlet.config.HttpOperation.perform(HttpOperation.java:42)
        at org.ocpsoft.rewrite.config.DefaultOperationBuilder$DefaultCompositeOperation.perform(DefaultOperationBuilder.java:56)
        at org.ocpsoft.rewrite.config.RuleBuilder.perform(RuleBuilder.java:136)
        at org.ocpsoft.rewrite.config.DefaultOperationBuilder$DefaultCompositeOperation.perform(DefaultOperationBuilder.java:56)
        at org.ocpsoft.rewrite.config.RuleBuilder.perform(RuleBuilder.java:136)
        at org.ocpsoft.rewrite.config.DefaultOperationBuilder$DefaultCompositeOperation.perform(DefaultOperationBuilder.java:56)
        at org.ocpsoft.rewrite.config.RuleBuilder.perform(RuleBuilder.java:136)
        at org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider.rewriteHttp(DefaultHttpRewriteProvider.java:182)
        at org.ocpsoft.rewrite.servlet.http.HttpRewriteProvider.rewrite(HttpRewriteProvider.java:43)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:242)
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
        ... 29 more
```

**Comment by lincolnthree** [comment]
Hi, I'm sorry for the *extremely* delayed response.

I believe the answer to your situation in Rule 2 is that PhaseBinding only supports value submission; hence, `PhaseBinding.to()` not `PhaseBinding.from() <-- doesn't exist`. 

This is due to the fact that evaluation of the Condition occurs outside of the JSF lifecycle, and even though you can defer a submission for a later phase, you cannot defer an EL value lookup because the value is indeed needed at the time of Condition evaluation.

It looks like you are trying to do internationalization in your app. There is a recommended solution for that here:
https://github.com/ocpsoft/rewrite/blob/master/documentation/src/main/asciidoc/configuration/i18n.asciidoc

It looks like you are trying to set a default locale or load one if the URL doesn't contain it, so If this doesn't work for you, you might consider storing and extracting the value in a `@SessionScoped` bean. That way the value would be available when you need it. You can even `@Inject` the bean directly into the ConfigurationProvider using the `rewrite-integration-cdi`. No need for a binding (though I suppose at that point you could bind to the bean without attempting to defer it using PhaseBinding).

I hope this is helpful.
