### ISSUE TITLE
Concurrency issue in RewriteViewHandler

### ISSUE THREAD

**Issue by dboldureanu** [ocpsoft/rewrite#215]
Looks that some locking mechanism is missing in [RewriteViewHandler.getProviders](https://github.com/ocpsoft/rewrite/blob/master/integration-faces/src/main/java/org/ocpsoft/rewrite/faces/RewriteViewHandler.java#L151)

This issue is very similar to https://github.com/ocpsoft/rewrite/issues/201, the exception in that one is in another class FacesRewriteLifecycleListener, but the code is almost the same. I assume same fix could be applied on this one as well?

```
Caused by: java.util.ConcurrentModificationException: null
	at java.util.ArrayList.sort(ArrayList.java:1456) ~[na:1.8.0_40]
	at java.util.Collections.sort(Collections.java:175) ~[na:1.8.0_40]
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.getProviders(RewriteViewHandler.java:151) ~[rewrite-integration-faces-2.0.12.Final.SP1.jar:2.0.12.Final.SP1]
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.getActionURL(RewriteViewHandler.java:123) ~[rewrite-integration-faces-2.0.12.Final.SP1.jar:2.0.12.Final.SP1]
	at com.sun.faces.renderkit.html_basic.FormRenderer.getActionStr(FormRenderer.java:250) ~[javax.faces-2.2.10.jar:2.2.10]
	at com.sun.faces.renderkit.html_basic.FormRenderer.encodeBegin(FormRenderer.java:143) ~[javax.faces-2.2.10.jar:2.2.10]
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:869) ~[javaee-api-7.0.jar:na]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1854) ~[javaee-api-7.0.jar:na]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javaee-api-7.0.jar:na]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javaee-api-7.0.jar:na]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456) ~[javax.faces-2.2.10.jar:2.2.10]
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133) ~[javax.faces-2.2.10.jar:2.2.10]
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:186) ~[rewrite-integration-faces-2.0.12.Final.SP1.jar:2.0.12.Final.SP1]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) ~[javax.faces-2.2.10.jar:2.2.10]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) ~[javax.faces-2.2.10.jar:2.2.10]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219) ~[javax.faces-2.2.10.jar:2.2.10]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647) ~[javaee-api-7.0.jar:na]
```

(rewrite-servlet 2.0.12)

**Comment by chkal** [comment]
Yeah, it looks like this is similar to #201. Would you be interested in providing a patch to fix this?

**Comment by dboldureanu** [comment]
Hello Christian, committed a patch, used solution from #201

**Comment by chkal** [comment]
Thanks a lot. The patch has been merged!

**Comment by lincolnthree** [comment]
Rewrite 3.0.0.Alpha10 has been released, and contains this fix. Apologies for the delay, we had some release trouble that is fixed now.
