### ISSUE TITLE
POM rewrite-parent SNAPSHOT

### ISSUE THREAD

**Issue by Tires** [ocpsoft/rewrite#231]
I was faced with the following exception:

```
 org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.ocpsoft.rewrite:r
ewrite-config-prettyfaces:jar:3.0.0.Alpha10
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.
java:349)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDe
scriptorReader.java:218)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependency
Collector.java:535)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyColl
ector.java:519)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java
:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java
:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.ja
va:254)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316
)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:1
72)
        at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:215)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:126)
        at com.intersult.maven_loader.MavenResolver.resolve(MavenResolver.java:161)
        at com.intersult.maven_loader.MavenHelper.resolve(MavenHelper.java:29)
        at com.intersult.maven_loader.MavenHelper.resolve(MavenHelper.java:26)
        at com.intersult.maven_loader.MavenResourceSet.initInternal(MavenResourceSet.java:69)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:669)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:136)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4928)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5058)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.ocpsoft.rewrite:rew
rite-parent:pom:3.0.0-SNAPSHOT in intersult-internal-repo (http://hv8-server.cy4:8092/nexus/content/groups/internal)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:177)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:226)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:978)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:796)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:325)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.
java:340)
        ... 33 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.ocpsoft.rewrite:rewrit
e-parent:pom:3.0.0-SNAPSHOT in intersult-internal-repo (http://hv8-server.cy4:8092/nexus/content/groups/internal)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:173)
        ... 38 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.ocpsoft.rewrite:rewrite-pa
rent:pom:3.0.0-SNAPSHOT in intersult-internal-repo (http://hv8-server.cy4:8092/nexus/content/groups/internal)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39
)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)

        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.j
ava:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 41 more
```

The reason is, in my opinion, that the parent POM entry from:

```
rewrite-config-prettyfaces-3.0.0.Alpha10.jar\META-INF\maven\org.ocpsoft.rewrite\rewrite-config-prettyfaces\
```

is pointing to:

```
   <parent>
      <artifactId>rewrite-parent</artifactId>
      <groupId>org.ocpsoft.rewrite</groupId>
      <version>3.0.0-SNAPSHOT</version>
      <relativePath>../</relativePath>
   </parent>
```
I was expecting 3.0.0.Alpha10 (version from Central). 3.0.0.Alpha6 has the correct version entry.

**Comment by chkal** [comment]
Yes, you are correct. It looks like the parent entry of this module is broken in 3.0.0.Alpha10. I've not idea how this happend. We usually use the maven-release-plugin for that which does all this automatically. Really weird.

Unfortunately there is no way to fix that. We cannot change the deployed artifacts in central. I'll double check this during the next release.

**Comment by Tires** [comment]
Hope Alpha11 will be released soon.
