### ISSUE TITLE
tel or mailto links Exception

### ISSUE THREAD

**Issue by djmj** [ocpsoft/rewrite#256]
I used a PrimeFaces _p:link_ with a phone _href_ value like _tel: 0123 456789_ and PrimeFaces calls _context.getExternalContext().encodeResourceURL(url)_. So rewrite module is invoked and fails with following exception. Is it a primefaces problem, that they should not call this function in case of a simple _href_?

java.net.URISyntaxException: Illegal character in opaque part at index 8: 
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3058)
	at java.net.URI.<init>(URI.java:588)
	at org.ocpsoft.urlbuilder.AddressBuilder.create(AddressBuilder.java:79)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteWrappedResponse.encodeURL(HttpRewriteWrappedResponse.java:394)

**Comment by chkal** [comment]
Actually `tel:0123 456789` isn't a valid URL/URI. The space character is not allowed. Unfortunately Rewrite currently fails for invalid URLs. You could have the latest snapshots a try. I recently committed some changes which will result in Rewrite handling invalid URLs more gracefully.

**Comment by djmj** [comment]
Thank you, i did not know that.I will test it later but removing the spaces made it work.

Is it possible to rewrite tel or mailto links at all?

**Comment by chkal** [comment]
Could work. Not sure. Never tried it. :smile:
