### ISSUE TITLE
Deployment Failure on Wildfly 18.0.1 with 3.4.3

### ISSUE THREAD

**Issue by codylerum** [ocpsoft/rewrite#285]
Was working fine on 3.4.2 but when switching to the new 3.4.3 release 
JDK 13
```
org.ocpsoft.rewrite.spi.GlobalParameterProvider [org.ocpsoft.rewrite.instance.WildcardParameterProvider<0>]
23:41:42,137 INFO  [org.ocpsoft.rewrite.servlet.RewriteFilter] (default task-1) Rewrite 3.4.3.Final initialized.
23:41:42,150 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /oss/s/search/search.xhtml: java.lang.NullPointerException
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.getProtectedViewsUnmodifiable(ViewHandlerWrapper.java:241)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.getProtectedViewsUnmodifiable(ViewHandlerWrapper.java:241)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.getProtectedViewsUnmodifiable(ViewHandlerWrapper.java:241)
	at javax.faces.api@3.0.0.Final//javax.faces.application.ViewHandlerWrapper.getProtectedViewsUnmodifiable(ViewHandlerWrapper.java:241)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.application.WebappLifecycleListener.sessionCreated(WebappLifecycleListener.java:190)
	at com.sun.jsf-impl@2.3.9.SP04//com.sun.faces.config.ConfigureListener.sessionCreated(ConfigureListener.java:394)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ApplicationListeners.sessionCreated(ApplicationListeners.java:317)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.SessionListenerBridge.sessionCreated(SessionListenerBridge.java:64)
	at io.undertow.core@2.0.27.Final//io.undertow.server.session.SessionListeners.sessionCreated(SessionListeners.java:52)
	at io.undertow.core@2.0.27.Final//io.undertow.server.session.InMemorySessionManager.createSession(InMemorySessionManager.java:189)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.spec.ServletContextImpl.getSession(ServletContextImpl.java:923)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.spec.HttpServletRequestImpl.getSession(HttpServletRequestImpl.java:418)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.servlet.SessionHolder.getSession(SessionHolder.java:61)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.context.beanstore.http.LazySessionBeanStore.getSession(LazySessionBeanStore.java:84)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.module.web.context.beanstore.http.AbstractSessionBeanStore.getLockStore(AbstractSessionBeanStore.java:120)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.contexts.beanstore.AttributeBeanStore.lock(AttributeBeanStore.java:251)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:90)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:84)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.core@3.1.2.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
	at deployment.oss.war//co.cfly.oss.aaa.ActiveUserManager$Proxy$_$$_WeldClientProxy.isLoggedIn(Unknown Source)
	at deployment.oss.war//co.cfly.oss.web.http.LoggedInFilter.doFilter(LoggedInFilter.java:64)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.oss.war//co.cfly.oss.web.http.ResponseFilter.doFilter(ResponseFilter.java:44)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.27.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.27.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow@18.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.0.27.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.0.27.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.core@2.0.27.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by codylerum** [comment]
@lincolnthree Looks like the travis build got broken with travis removing the oraclejdk7 and oraclejdk8 builds. I threw in a PR to get that fixed.

However it appears things got broken with the JSF 2.3 API update.

Before API Update: Working
https://travis-ci.com/codylerum/rewrite/builds/138768259

After API Update Fails
https://travis-ci.com/codylerum/rewrite/builds/138768633

**Comment by kalgon** [comment]
Could someone take a look at the PRs? This problem makes Rewrite totally unusable with JSF 2.3.

Thanks!

**Comment by lincolnthree** [comment]
Hey folks. Working on it now. Thanks so much for finding & patching this.

**Comment by commodis** [comment]
This issue seems closable due to PR  #287

**Comment by lincolnthree** [comment]
Thanks @codylerum !
